cursor            #ffb4a2
cursor_text_color #561f11

foreground            #f1dfdb
background            #140c0a
selection_foreground  #442a23
selection_background  #e7bdb3
url_color             #e7bdb3

#: black 000000 767676
color0  #1a110f
color8  #3d3230
#: red cc0403 f2201f
color1  #0f0a08
color9  #764f3a
#: green 19cb00 23fd00
color2  #e7bdb3
color10 #ffdad2
#: yellow cecb00 fffd00
color3  #dac58c
color11 #f7e1a6
#: blue 0d73cc 1a8fff
color4  #723425
color12 #ffb4a2
#: magenta cb1ed1 fd28ff
color5  #5d3f38
color13 #e7bdb3
#: cyan 0dcdcd 14ffff
color6  #544519
color14 #dac58c
#: white dddddd ffffff
color7  #d8c2bd
color15 #f1dfdb

mark1_foreground #3a0a02
mark1_background #ffdad2
mark2_foreground #2c1510
mark2_background #ffdad2
mark3_foreground #241a00
mark3_background #f7e1a6

active_tab_foreground #561f11
active_tab_background #ffb4a2
inactive_tab_foreground #ffdad2
inactive_tab_background #723425

active_border_color #ffb4a2
inactive_border_color #561f11
# bell_border_color #ff5a00
