# font_family JetBrains Mono Nerd Font
font_size 14

cursor_shape beam
cursor_trail 20
cursor_blink_interval 0.5 ease-in-out
scrollbar never
background_opacity 0.9
background_blur 1
window_padding_width 8
confirm_os_window_close 0
text_fg_override_threshold 1
# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family='JetBrainsMono Nerd Font' postscript_name=JetBrainsMonoNF-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS