-- ~/.config/matugen/templates/neovim.lua
-- Auto-generated by matugen — do not edit manually.
-- Regenerate: matugen image /path/to/wallpaper.jpg

local M = {}

M.palette = {
  -- Core surface / background
  background                = "#1a110f",
  on_background             = "#f1dfdb",
  surface                   = "#1a110f",
  on_surface                = "#f1dfdb",
  surface_variant           = "#534340",
  on_surface_variant        = "#d8c2bd",

  -- Surface containers (lowest → highest)
  surface_container_lowest  = "#140c0a",
  surface_container_low     = "#231917",
  surface_container         = "#271d1b",
  surface_container_high    = "#322825",
  surface_container_highest = "#3d3230",

  -- Primary
  primary                   = "#ffb4a2",
  on_primary                = "#561f11",
  primary_container         = "#723425",
  on_primary_container      = "#ffdad2",

  -- Secondary
  secondary                 = "#e7bdb3",
  on_secondary              = "#442a23",
  secondary_container       = "#5d3f38",
  on_secondary_container    = "#ffdad2",

  -- Tertiary
  tertiary                  = "#dac58c",
  on_tertiary               = "#3c2f04",
  tertiary_container        = "#544519",
  on_tertiary_container     = "#f7e1a6",

  -- Error
  error                     = "#ffb4ab",
  on_error                  = "#690005",
  error_container           = "#93000a",
  on_error_container        = "#ffdad6",

  -- Outline / borders
  outline                   = "#a08c88",
  outline_variant           = "#534340",

  -- Inverse
  inverse_surface           = "#f1dfdb",
  inverse_on_surface        = "#392e2c",
  inverse_primary           = "#904b3a",
}

return M
