# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

source = colors.conf
$font = Mojangles

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    color = $secondary
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = $secondary $primary 90deg
    check_color = $tertiary $secondary 180deg
    fail_color = $error $on_error 90deg

    font_color = $primary
    fade_on_empty = false
    rounding = 15

    font_family = $font
    placeholder_text = Enter Password
    fail_text = $PAMFAIL

    # uncomment if you wish to display a message during authentication
    # check_text = Authenticating...

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 35%
    halign = center
    valign = bottom
}

# TIME
label {
    monitor =
    text = $TIME12 # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font
    color = $primary

    position = 0, 20%
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font
    color = $secondary

    position = 0, 30%
    halign = center
    valign = center
}

$button_font = JetBrainsMono Nerd Font Mono

# LOGOUT
label {
    monitor =
    text = 
    font_size = 80
    font_family = $button_font
    color = $secondary

    position = -10%, 10%
    halign = center
    valign = bottom

    onclick = niri msg action quit
}

# SHUTDOWN
label {
    monitor =
    text = 
    font_size = 80
    font_family = $button_font
    color = $secondary

    position = 0, 10%
    halign = center
    valign = bottom

    onclick = systemctl poweroff
}

# SLEEP
label {
    monitor =
    text = 󰤄
    font_size = 80
    font_family = $button_font
    color = $secondary

    position = 10%, 10%
    halign = center
    valign = bottom

    onclick = systemctl sleep
}

# PROFILE
image {
    monitor =
    size = 100
    path = ~/.config/hypr/8665d333aad056c944f44b5db3125e97.webp

    position = 0, 45%
    halign = center
    valign = bottom

    rounding = -1
    border_color = $primary $secondary 0deg
}

#label {
#    monitor =
#    text = $LAYOUT[en,ru]
#    font_size = 24
#    onclick = hyprctl switchxkblayout all next
#
#    position = 250, -20
#    halign = center
#    valign = center
#}
